services:
  reload-server:
    container_name: reload-server
    build:
      context: .
      dockerfile: ./.simple-web-client/reload-server/reload-server.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - dev

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.simple-web-client/nginx/nginx.Dockerfile
    ports:
      - "4200:443"
    volumes:
      - ./.simple-web-client/nginx/certs:/certs:ro
    depends_on:
      - reload-server
    networks:
      - dev
    develop:
      watch:
        - action: sync+exec
          path: ./app
          target: /html
          exec:
            command: ["./reload.sh"]
        - action: sync+exec
          path: ./.simple-web-client/lib
          target: /html/simple-web-client
          exec:
            command: ["./reload.sh"]

networks:
  dev:
    name: dev
